name: Sync to Other Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4

      - name: Configure Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Push to target repo
        env:
          TARGET_REPO: org-dup-02/project-for-dup
          TARGET_BRANCH: main
          GH_TOKEN: ${{ secrets.DUP_REPO_TOKEN }}
        run: |
          git remote add target https://x-access-token:${GH_TOKEN}@github.com/${TARGET_REPO}.git
          git push target ${TARGET_BRANCH} --force
